########################################################################################################################
#                                                      ___                  _                                          #
#                    /\  /\___  _ __  _ __   ___ _ __ / __\___  _   _ _ __ | |_ ___ _ __                               #
#                   / /_/ / _ \| '_ \| '_ \ / _ \ '__/ /  / _ \| | | | '_ \| __/ _ \ '__|                              #
#                  / __  / (_) | |_) | |_) |  __/ | / /__| (_) | |_| | | | | ||  __/ |                                 #
#                  \/ /_/ \___/| .__/| .__/ \___|_| \____/\___/ \__,_|_| |_|\__\___|_|                                 #
#                              |_|   |_|                                                                               #
#                                                                                                         By MrWarzo0  #
########################################################################################################################

# Liste des messages liés aux hoppers #
hoppers:
  limit: 40
  name: "Hoppers"
  cantplace: "§cLimite de hoppers atteinte !"

# Liste des messages liés aux observers #
observers:
  limit: 40
  name: "Observers"
  cantplace: "§cLimite d'observers atteinte !"

# Liste des permissions utilisées
permissions:
  reloadcfg: "hc.reloadcfg"
  reloadchunk: "hc.reloadchunk"

# Liste des différents messages
other:
  usage: "§cUsage : /hoppercounter §6reloadcfg §c| §6reloadchunk"
  reloadcfg: "§a\"config.yml\" a bien été rechargé."
  reloadchunk: "§aLe chunk à bien été rechargé."
  noperm: "§cVous n'avez pas la permmission."
  noplayer: "&cVous devez etre un joueur pour effectue cette commande."

