name: HopperCounter
main: fr.mrwarzo.hoppercounter.Main
version: 1.0.0
api-version: 1.13
description: Plugin de comptage d'hoppers
author: MrWarzo
commands:
  hoppercounter:
    description: Informations sur HopperCounter
    aliases: [hc]